package service;

import java.time.LocalDate;
import java.util.List;

import data.ItemManager;
import data.LoanManager;
import data.UserManager;
import exception.ItemNotFoundException;
import exception.ItemUnavailableException;
import exception.UserNotFoundException;
import model.Item;
import model.Loan;
import model.Member;
import model.User;

/*
 Description:
 Coordinates business logic across ItemManager, UserManager, and
LoanManager. The CLI layer (Main) talks to LibraryService rather
than the managers directly, keeping business rules (e.g. "you
can't check out an item that is already on loan") in one place.
Inputs: member IDs, item IDs, loan IDs, and search keywords.
Processing: validates pre-conditions, delegates DB work to the
managers, and enforces business rules between them.
Outputs: domain objects (Items, Loans) or void for state changes.
 */
public class LibraryService {

    private static final int DEFAULT_LOAN_DAYS = 14;

    private final ItemManager itemManager;
    private final UserManager userManager;
    private final LoanManager loanManager;

    public LibraryService(ItemManager itemManager,
                          UserManager userManager,
                          LoanManager loanManager) {
        this.itemManager = itemManager;
        this.userManager = userManager;
        this.loanManager = loanManager;
    }

    /**
     * Check out an item for a member. Rules enforced here:
     *   1. The member must exist.
     *   2. The item must exist.
     *   3. The item must currently be available.
     *
     * On success, creates a Loan record and flips the item to unavailable.
     */
    public Loan checkoutItem(int memberId, int itemId)
            throws UserNotFoundException,
                   ItemNotFoundException,
                   ItemUnavailableException {

        User user = userManager.getById(memberId);
        if (!(user instanceof Member)) {
            throw new UserNotFoundException(
                    "User " + memberId + " is not a member and cannot borrow items.");
        }
        Member member = (Member) user;

        Item item = itemManager.getById(itemId);
        if (!item.isAvailable()) {
            throw new ItemUnavailableException(item.getId(), item.getTitle());
        }

        LocalDate today = LocalDate.now();
        Loan loan = new Loan(
                0,                          // auto-generated by DB
                item,
                member,
                today,
                today.plusDays(DEFAULT_LOAN_DAYS),
                null                        // not yet returned
        );

        loanManager.add(loan);
        itemManager.setAvailability(item.getId(), false);

        return loan;
    }

    /**
     * Return a previously checked-out item. Looks up the active loan
     * for the given item, stamps the return date, and marks the item
     * as available again.
     */
    public Loan returnItem(int itemId)
            throws ItemNotFoundException, UserNotFoundException {

        Loan loan = loanManager.findActiveLoanForItem(itemId);
        loan.setReturnDate(LocalDate.now());
        loanManager.update(loan);
        itemManager.setAvailability(itemId, true);
        return loan;
    }

    /** Delegate keyword search to ItemManager. */
    public List<Item> searchItems(String keyword) {
        return itemManager.search(keyword);
    }

    /** Delegate keyword search to UserManager. */
    public List<User> searchUsers(String keyword) {
        return userManager.search(keyword);
    }

    public List<Loan> getOverdueLoans() {
        return loanManager.getOverdueLoans();
    }

    public List<Loan> getMemberLoans(int memberId) {
        return loanManager.getLoansByMember(memberId);
    }
}
